---
version: "3.8"
services:
  #postgres db
  db:
    image: postgres
    container_name: postgres_container
    restart: unless-stopped
    shm_size: 128mb
    environment:
      - POSTGRES_PASSWORD=75?4jHur^gn8u4kt^
      - POSTGRES_USER=postgres
      - POSTGRES_DB=pg16
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - /postgresql/data":/var/lib/postgresql/data
    command:
      - "postgres"
      - "-c"
      - "max_connections=50"
      - "-c"
      - "shared_buffers=1GB"
      - "-c"
      - "effective_cache_size=4GB"
      - "-c"
      - "work_mem=16MB"
      - "-c"
      - "maintenance_work_mem=512MB"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "temp_file_limit=10GB"
      - "-c"
      - "log_min_duration_statement=200ms"
      - "-c"
      - "idle_in_transaction_session_timeout=10s"
      - "-c"
      - "lock_timeout=1s"
      - "-c"
      - "statement_timeout=60s"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.max=10000"
      - "-c"
      - "pg_stat_statements.track=all"
    networks:
      - backbone
    ports:
      - 5432:5432/tcp
  #postgres ui
  pgadmin:
    image: dpage/pgadmin4
    container_name: pg_admin
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=75?4jHur^gn8u4kt^
    networks:
      - backbone
    ports:
      - 5050:80/tcp


# PHP Service
  php:
    build:
      context: .
      dockerfile: Dockerfile
    image: php:8.1
    container_name: php
    restart: unless-stopped
    tty: true
    #environment:
    #  - PHP_INI_SCAN_DIR= /etc/php/conf.d/
    ports:
      - 9000:9000/tcp
    expose:
      - "9000"
    volumes:
      - ./php-ini:/usr/local/etc/php/custom.d
      - .:/var/www/app/
    networks:
      - backbone

  # Nginx Service
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./storage/app/public/:/var/www/app/storage/app/public
      #- ./nginx/ca-cert.pem:/etc/ssl/certs/ca-cert.pem
      #- ./nginx/cakey.pem:/etc/ssl/private/cakey.pem
      - .:/var/www/app/
    depends_on:
      - php
    networks:
      - backbone
  
  #nodejs
  npm:
    image: node:lts-alpine3.19
    container_name: npm
    build:
      context: .
    volumes: 
      - .:/var/www/app/
    working_dir: /var/www/app/public
    ports:
      - "${VITE_PORT:-5173}:${VITE_PORT:-5173}"
    expose:
      - "5173"
    depends_on:
      - php
      - nginx
      - pgadmin
    environment:
      - NODE_ENV=production
    command: "npm run dev"
    networks:
      - backbone

#network
networks:
  backbone:
    driver: bridge